import type { VaseSlicerSettings, VaseToolpath } from '../slicer';

export function shouldEmitOrcaMetadata(settings: VaseSlicerSettings): boolean {
    return settings.printerModelId === 'bambu-p1s';
}

export function buildOrcaMetadataHeader(
    toolpath: VaseToolpath,
    settings: VaseSlicerSettings,
    filamentMeta: { type: string; densityGcm3: number; costPerKg: number }
): string[] {
    const generatedAt = formatLocalTimestamp(new Date());
    const bedWidth = Math.round(settings.bedWidthMm);
    const bedDepth = Math.round(settings.bedDepthMm);
    const maxHeight = Math.round(settings.maxPrintHeightMm);
    const estimatedPrintSeconds = estimatePrintTimeSeconds(toolpath);
    const estimatedPrintText = formatDuration(estimatedPrintSeconds);
    const startGcodeCfg = escapeConfigValue(settings.startGcode);
    const endGcodeCfg = escapeConfigValue(settings.endGcode);
    const travelSpeedMmPerSec = Math.round(settings.travelSpeedMmPerSec);
    const printSpeedMmPerSec = Math.round(settings.printSpeedMmPerSec);
    const firstLayerPrintSpeedMmPerSec = Math.round(settings.firstLayerPrintSpeedMmPerSec);
    const brimWidthMm = Math.max(0, settings.brimWidthMm);
    const brimGapMm = Math.max(0, settings.brimGapMm);
    const brimType = brimWidthMm > 0 ? 'auto_brim' : 'no_brim';

    return [
        '; HEADER_BLOCK_START',
        `; generated by OrcaSlicer 2.3.1 on ${generatedAt}`,
        `; model printing time: ${estimatedPrintText}; total estimated time: ${estimatedPrintText}`,
        `; estimated first layer printing time (normal mode) = ${Math.max(1, Math.round(estimatedPrintSeconds * 0.08))}s`,
        `; total layer number: ${toolpath.layerCount}`,
        '; model label id: 195',
        `; filament_density: ${filamentMeta.densityGcm3.toFixed(2)}`,
        `; filament_diameter: ${settings.filamentDiameter.toFixed(2)}`,
        `; max_z_height: ${toolpath.estimatedHeight.toFixed(2)}`,
        '; HEADER_BLOCK_END',
        '',
        '; CONFIG_BLOCK_START',
        '; accel_to_decel_enable = 1',
        '; accel_to_decel_factor = 50%',
        '; activate_air_filtration = 0',
        '; activate_chamber_temp_control = 0',
        '; adaptive_bed_mesh_margin = 0',
        '; adaptive_pressure_advance = 0',
        '; adaptive_pressure_advance_bridges = 0',
        '; adaptive_pressure_advance_overhangs = 0',
        '; additional_cooling_fan_speed = 70',
        '; align_infill_direction_to_model = 0',
        '; auxiliary_fan = 1',
        '; bbl_use_printhost = 0',
        '; bed_mesh_max = 99999,99999',
        '; bed_mesh_min = -99999,-99999',
        '; bed_mesh_probe_distance = 50,50',
        `; brim_type = ${brimType}`,
        `; brim_width = ${brimWidthMm.toFixed(2)}`,
        `; brim_object_gap = ${brimGapMm.toFixed(2)}`,
        '; close_fan_the_first_x_layers = 1',
        '; complete_print_exhaust_fan_speed = 70',
        '; curr_bed_type = High Temp Plate',
        '; default_acceleration = 10000',
        '; default_jerk = 0',
        '; detect_overhang_wall = 1',
        '; disable_m73 = 0',
        '; dont_slow_down_outer_wall = 0',
        '; draft_shield = disabled',
        '; during_print_exhaust_fan_speed = 70',
        '; elefant_foot_compensation = 0.15',
        '; emit_machine_limits_to_gcode = 1',
        '; enable_arc_fitting = 1',
        '; enable_overhang_speed = 1',
        '; fan_max_speed = 100',
        '; fan_min_speed = 100',
        '; fan_speedup_overhangs = 1',
        '; filament_colour = #26A69A',
        `; filament_cost = ${filamentMeta.costPerKg.toFixed(0)}`,
        '; travel_acceleration = 10000',
        '; first_layer_acceleration = 500',
        '; bridge_acceleration = 50%',
        '; gcode_comments = 0',
        '; gcode_label_objects = 1',
        '; gcode_flavor = marlin',
        '; has_scarf_joint_seam = 0',
        '; host_type = octoprint',
        '; hot_plate_temp = 55',
        '; hot_plate_temp_initial_layer = 55',
        '; infill_direction = 45',
        '; infill_wall_overlap = 15%',
        '; initial_layer_infill_speed = 105',
        `; initial_layer_line_width = ${settings.firstLayerLineWidth.toFixed(2)}`,
        '; initial_layer_print_height = 0.2',
        '; initial_layer_travel_speed = 100%',
        '; inner_wall_acceleration = 10000',
        '; inner_wall_line_width = 0.45',
        '; inner_wall_speed = 300',
        '; layer_change_gcode = ',
        '; long_retractions_when_cut = 0',
        '; printer_vendor = Bambu Lab',
        '; printer_model = Bambu Lab P1S',
        '; printer_settings_id = Bambu Lab P1S 0.4 nozzle',
        '; print_settings_id = Implicit Vase Mode',
        `; filament_settings_id = ${settings.filamentProfileName}`,
        '; printer_structure = corexy',
        '; printer_technology = FFF',
        '; printer_variant = 0.4',
        '; machine_max_speed_x = 500,200',
        '; machine_max_speed_y = 500,200',
        '; machine_max_speed_z = 20,20',
        '; machine_max_speed_e = 30,30',
        '; machine_max_acceleration_x = 20000,20000',
        '; machine_max_acceleration_y = 20000,20000',
        '; machine_max_acceleration_z = 500,200',
        '; machine_max_acceleration_e = 5000,5000',
        '; machine_max_jerk_x = 9,9',
        '; machine_max_jerk_y = 9,9',
        '; machine_max_jerk_z = 3,3',
        '; machine_max_jerk_e = 2.5,2.5',
        '; machine_load_filament_time = 29',
        '; machine_max_acceleration_extruding = 20000,20000',
        '; machine_max_acceleration_retracting = 5000,5000',
        '; machine_max_acceleration_travel = 9000,9000',
        '; machine_pause_gcode = M400 U1',
        `; machine_start_gcode = ${startGcodeCfg}`,
        `; machine_end_gcode = ${endGcodeCfg}`,
        '; machine_tool_change_time = 0',
        '; machine_unload_filament_time = 28',
        '; max_layer_height = 0.28',
        '; min_layer_height = 0.08',
        '; min_bead_width = 85%',
        '; nozzle_height = 4.2',
        `; nozzle_diameter = ${settings.nozzleDiameter.toFixed(2)}`,
        `; filament_diameter = ${settings.filamentDiameter.toFixed(2)}`,
        '; filament_density = 1.24',
        `; filament_type = ${filamentMeta.type}`,
        '; filament_vendor = Generic',
        '; filament_flow_ratio = 1',
        '; filament_max_volumetric_speed = 12',
        '; filament_start_gcode = ',
        '; filament_end_gcode = ',
        '; nozzle_temperature_range_high = 240',
        '; nozzle_temperature_range_low = 190',
        '; print_flow_ratio = 1',
        `; nozzle_temperature = ${settings.nozzleTempC.toFixed(0)}`,
        `; nozzle_temperature_initial_layer = ${settings.nozzleTempC.toFixed(0)}`,
        `; first_layer_temperature = ${settings.nozzleTempC.toFixed(0)}`,
        `; bed_temperature = ${settings.bedTempC.toFixed(0)}`,
        `; first_layer_bed_temperature = ${settings.bedTempC.toFixed(0)}`,
        `; layer_height = ${settings.layerHeight.toFixed(2)}`,
        `; line_width = ${settings.lineWidth.toFixed(2)}`,
        `; first_layer_line_width = ${settings.firstLayerLineWidth.toFixed(2)}`,
        `; first_layer_bed_temperature = ${settings.bedTempC.toFixed(0)}`,
        '; overhang_fan_speed = 100',
        '; overhang_fan_threshold = 50%',
        '; outer_wall_acceleration = 5000',
        '; outer_wall_line_width = 0.42',
        '; outer_wall_speed = 200',
        '; pressure_advance = 0.02',
        '; print_compatible_printers = "Bambu Lab P1S 0.4 nozzle"',
        '; print_order = default',
        '; print_sequence = by layer',
        '; printable_height = 250',
        '; pressure_advance = 0.02',
        '; reduce_crossing_wall = 0',
        '; retract_length_toolchange = 2',
        '; retraction_length = 0.8',
        '; retraction_speed = 30',
        '; seam_position = aligned',
        '; silent_mode = 0',
        '; single_extruder_multi_material = 1',
        '; skirt_loops = 0',
        '; skirt_distance = 2',
        '; slicing_mode = regular',
        '; slow_down_for_layer_cooling = 1',
        '; slow_down_layer_time = 8',
        '; wall_loops = 1',
        '; top_shell_layers = 0',
        '; bottom_shell_layers = 3',
        '; sparse_infill_density = 0%',
        '; sparse_infill_pattern = crosshatch',
        '; sparse_infill_line_width = 0.45',
        '; sparse_infill_speed = 270',
        '; support_type = normal(auto)',
        '; enable_support = 0',
        '; support_threshold_angle = 30',
        '; support_top_z_distance = 0.2',
        '; support_bottom_z_distance = 0.2',
        '; support_object_xy_distance = 0.35',
        '; textured_cool_plate_temp = 40',
        '; textured_cool_plate_temp_initial_layer = 40',
        '; textured_plate_temp = 55',
        '; textured_plate_temp_initial_layer = 55',
        '; timelapse_type = 0',
        '; top_surface_pattern = monotonicline',
        '; travel_jerk = 12',
        '; travel_speed_z = 0',
        '; wall_direction = auto',
        '; wall_generator = classic',
        '; wall_sequence = inner wall/outer wall',
        '; wipe = 1',
        '; wipe_distance = 1',
        '; z_hop = 0.4',
        '; z_hop_types = Auto Lift',
        '; z_offset = 0',
        `; printable_area = 0x0,${bedWidth}x0,${bedWidth}x${bedDepth},0x${bedDepth}`,
        `; printable_height = ${maxHeight}`,
        '; spiral_mode = 1',
        '; spiral_mode_smooth = 0',
        '; spiral_mode_max_xy_smoothing = 200%',
        `; print_speed = ${printSpeedMmPerSec}`,
        `; outer_wall_speed = ${printSpeedMmPerSec}`,
        `; travel_speed = ${travelSpeedMmPerSec}`,
        `; initial_layer_speed = ${firstLayerPrintSpeedMmPerSec}`,
        '; use_relative_e_distances = 1',
        '; wipe = 1',
        '; timelapse_type = 0',
        '; start_end_points = 30x-3,54x245',
        '; CONFIG_BLOCK_END',
        '',
        `; external perimeters extrusion width = ${settings.lineWidth.toFixed(2)}mm`,
        '; perimeters extrusion width = 0.45mm',
        '; infill extrusion width = 0.45mm',
        '; solid infill extrusion width = 0.42mm',
        '; top infill extrusion width = 0.42mm',
        `; first layer extrusion width = ${settings.firstLayerLineWidth.toFixed(2)}mm`,
        '',
        '; EXECUTABLE_BLOCK_START',
    ];
}

export function buildExcludeObjectDefineLine(toolpath: VaseToolpath, settings: VaseSlicerSettings): string | null {
    if (settings.printerModelId !== 'elegoo-neptune-4-max' || toolpath.points.length === 0) {
        return null;
    }

    let minX = Number.POSITIVE_INFINITY;
    let maxX = Number.NEGATIVE_INFINITY;
    let minY = Number.POSITIVE_INFINITY;
    let maxY = Number.NEGATIVE_INFINITY;

    for (const point of toolpath.points) {
        minX = Math.min(minX, point.x);
        maxX = Math.max(maxX, point.x);
        minY = Math.min(minY, point.z);
        maxY = Math.max(maxY, point.z);
    }

    if (!Number.isFinite(minX) || !Number.isFinite(maxX) || !Number.isFinite(minY) || !Number.isFinite(maxY)) {
        return null;
    }

    const marginMm = Math.max(2, settings.nozzleDiameter * 5);
    const x0 = clamp(minX - marginMm, 0, settings.bedWidthMm);
    const x1 = clamp(maxX + marginMm, 0, settings.bedWidthMm);
    const y0 = clamp(minY - marginMm, 0, settings.bedDepthMm);
    const y1 = clamp(maxY + marginMm, 0, settings.bedDepthMm);
    const centerX = (x0 + x1) * 0.5;
    const centerY = (y0 + y1) * 0.5;

    return `EXCLUDE_OBJECT_DEFINE NAME=implicit_vase_id_0_copy_0 CENTER=${formatCompactGcodeNumber(centerX)},${formatCompactGcodeNumber(centerY)} POLYGON=[[${formatCompactGcodeNumber(x0)},${formatCompactGcodeNumber(y0)}],[${formatCompactGcodeNumber(x1)},${formatCompactGcodeNumber(y0)}],[${formatCompactGcodeNumber(x1)},${formatCompactGcodeNumber(y1)}],[${formatCompactGcodeNumber(x0)},${formatCompactGcodeNumber(y1)}]]`;
}

export function inferFilamentMetadata(settings: VaseSlicerSettings): { type: string; densityGcm3: number; costPerKg: number } {
    const probe = `${settings.filamentProfileId} ${settings.filamentProfileName}`.toUpperCase();
    if (probe.includes('PETG')) {
        return { type: 'PETG', densityGcm3: 1.27, costPerKg: 24 };
    }
    if (probe.includes('ABS')) {
        return { type: 'ABS', densityGcm3: 1.04, costPerKg: 22 };
    }
    if (probe.includes('ASA')) {
        return { type: 'ASA', densityGcm3: 1.07, costPerKg: 28 };
    }
    if (probe.includes('TPU')) {
        return { type: 'TPU', densityGcm3: 1.21, costPerKg: 35 };
    }
    if (probe.includes('PA') || probe.includes('NYLON')) {
        return { type: 'PA', densityGcm3: 1.14, costPerKg: 40 };
    }

    return { type: 'PLA', densityGcm3: 1.24, costPerKg: 20 };
}

function formatCompactGcodeNumber(value: number): string {
    const rounded = Math.round(value * 1000) / 1000;
    return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(3).replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1');
}

function estimatePrintTimeSeconds(toolpath: VaseToolpath): number {
    if (toolpath.points.length < 2) {
        return 0;
    }

    let seconds = 0;
    for (let i = 1; i < toolpath.points.length; i++) {
        const a = toolpath.points[i - 1];
        const b = toolpath.points[i];
        const distance = Math.hypot(b.x - a.x, b.y - a.y, b.z - a.z);
        const speed = Math.max(1e-6, b.speedMmPerSec);
        seconds += distance / speed;
    }

    return Math.max(0, Math.round(seconds));
}

function formatDuration(totalSeconds: number): string {
    const clamped = Math.max(0, Math.round(totalSeconds));
    const hours = Math.floor(clamped / 3600);
    const minutes = Math.floor((clamped % 3600) / 60);
    const seconds = clamped % 60;

    if (hours > 0) {
        return `${hours}h ${minutes}m ${seconds}s`;
    }
    if (minutes > 0) {
        return `${minutes}m ${seconds}s`;
    }
    return `${seconds}s`;
}

function escapeConfigValue(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/\r\n/g, '\\n')
        .replace(/\n/g, '\\n');
}

function formatLocalTimestamp(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    const seconds = String(date.getSeconds()).padStart(2, '0');
    return `${year}-${month}-${day} at ${hours}:${minutes}:${seconds}`;
}

function clamp(value: number, min: number, max: number): number {
    return Math.max(min, Math.min(max, value));
}
