import { clamp } from './math';
import type { VaseSlicerSettings } from './config';
import type { ToolpathPoint, VaseToolpath } from './types';
import { calculateExtrusionPerMm } from './toolpath';
import {
    buildExcludeObjectDefineLine,
    buildOrcaMetadataHeader,
    inferFilamentMetadata,
} from './gcode-metadata';
import {
    expandGcodeTemplate,
    getDefaultEndGcode,
    getDefaultStartGcode,
    mmPerSecToFeedrate,
    parseGcodeLines,
} from './gcode-template';

/** Emit the final G-code for a finished toolpath. */
export function buildGcode(toolpath: VaseToolpath, settings: VaseSlicerSettings, extraHeaderLines?: string[]): string {
    if (toolpath.points.length < 2) {
        throw new Error('Vase slicing produced no valid path.');
    }

    const lines: string[] = [];
    const p0 = toolpath.points[0];
    const configuredFanPwm = percentToPwm(settings.fanPercent);
    const filamentMeta = inferFilamentMetadata(settings);

    lines.push(...buildOrcaMetadataHeader(toolpath, settings, filamentMeta));

    const excludeObjectDefine = buildExcludeObjectDefineLine(toolpath, settings);
    if (excludeObjectDefine) {
        lines.push(excludeObjectDefine);
    }

    lines.push('; Implicit vase-mode toolpath');
    lines.push('; Generated by Implicit');
    lines.push(`; Slicer mode: ${settings.slicerMode}`);
    lines.push(`; Layers: ${toolpath.layerCount}`);
    lines.push(`; Points per layer: ${toolpath.pointsPerLayer}`);
    lines.push(`; Model scale (mm/SDF-unit): ${settings.modelScale.toFixed(2)}`);
    lines.push(`; Printer: ${settings.printerModelName} (${settings.printerModelId})`);
    lines.push(`; Filament: ${settings.filamentProfileName} (${settings.filamentProfileId})`);
    lines.push(`; Filament type: ${filamentMeta.type}`);
    lines.push(`; Filament density (g/cm3): ${filamentMeta.densityGcm3.toFixed(2)}`);
    lines.push(`; Filament cost (per kg): ${filamentMeta.costPerKg.toFixed(2)}`);
    lines.push(`; Bed size (mm): ${settings.bedWidthMm.toFixed(1)} x ${settings.bedDepthMm.toFixed(1)}`);
    lines.push(`; Max print height (mm): ${settings.maxPrintHeightMm.toFixed(1)}`);
    lines.push(`; Nozzle diameter (mm): ${settings.nozzleDiameter.toFixed(2)}`);
    lines.push(`; Nozzle temperature (C): ${settings.nozzleTempC.toFixed(0)}`);
    lines.push(`; Bed temperature (C): ${settings.bedTempC.toFixed(0)}`);
    lines.push(`; Fan speed (%): ${settings.fanPercent.toFixed(0)}`);
    lines.push(`; Line width (mm): ${settings.lineWidth.toFixed(3)}`);
    lines.push(`; First layer line width (mm): ${settings.firstLayerLineWidth.toFixed(3)}`);
    lines.push(`; Layer height (mm): ${settings.layerHeight.toFixed(3)}`);
    if (settings.maxLayerHeightMm > settings.layerHeight) {
        lines.push(`; Max layer height (mm): ${settings.maxLayerHeightMm.toFixed(3)}`);
    }
    lines.push(`; Target segment length (mm): ${settings.targetSegmentMm.toFixed(3)}`);
    lines.push(`; First layer print speed (mm/s): ${settings.firstLayerPrintSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Print speed (mm/s): ${settings.printSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Minimum layer time (s): ${settings.minLayerTimeSec.toFixed(2)}`);
    lines.push(`; Travel speed (mm/s): ${settings.travelSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Bottom layers: ${settings.bottomLayers}`);
    lines.push(`; Brim width (mm): ${settings.brimWidthMm.toFixed(2)}`);
    lines.push(`; Brim gap (mm): ${settings.brimGapMm.toFixed(2)}`);
    lines.push(`; Iso snap factor: ${settings.sliceIsoSnapFactor.toFixed(2)}`);
    lines.push(`; Contour alignment: ${settings.enableContourAlignment ? 'on' : 'off'}`);
    lines.push(`; Move merging: ${settings.enableMoveMerging ? 'on' : 'off'}`);
    lines.push(`; First layer extrusion/mm: ${calculateExtrusionPerMm(settings, settings.firstLayerLineWidth).toFixed(5)}`);
    lines.push(`; Extrusion/mm: ${calculateExtrusionPerMm(settings, settings.lineWidth).toFixed(5)}`);
    lines.push(`; Estimated height (mm): ${toolpath.estimatedHeight.toFixed(3)}`);
    for (const summary of toolpath.postprocessSummaries ?? []) {
        lines.push(`; Postprocess step ${summary.stepIndex + 1}: ${summary.name}${summary.scriptId ? ` (${summary.scriptId})` : ''}`);
        lines.push(`; Postprocess points: ${summary.inputPointCount} -> ${summary.outputPointCount} before merge`);
        lines.push(`; Postprocess runtime (ms): ${summary.durationMs.toFixed(2)}`);
        for (const note of summary.notes) {
            lines.push(`; Postprocess note: ${note}`);
        }
    }
    for (const line of extraHeaderLines ?? []) {
        lines.push(line.startsWith(';') ? line : `; ${line}`);
    }
    const rawPathPoints = toolpath.layerCount * toolpath.pointsPerLayer;
    const mergedPathPoints = toolpath.points.length;
    const removedPathPoints = Math.max(0, rawPathPoints - mergedPathPoints);
    const mergeReductionPct = rawPathPoints > 0 ? (removedPathPoints / rawPathPoints) * 100 : 0;
    lines.push(`; Move merge: ${removedPathPoints} points removed (${mergeReductionPct.toFixed(1)}%)`);
    const startLines = parseGcodeLines(settings.startGcode, getDefaultStartGcode());
    for (const line of startLines) {
        lines.push(expandGcodeTemplate(line, settings));
    }
    // Normalize motion/extrusion modes regardless of custom start G-code state.
    lines.push('G21');
    lines.push('G90');
    // Force relative extrusion for exported toolpaths so each move carries only its local extrusion delta.
    lines.push('M83');
    // Keep first layer fan off for adhesion, then restore configured fan after layer 0.
    lines.push('M106 S0');
    const emittedBrim = appendBrimGcode(
        lines,
        toolpath,
        settings,
        Math.max(settings.layerHeight, p0.y),
        calculateExtrusionPerMm(settings, settings.firstLayerLineWidth)
    );
    lines.push('; FEATURE: Travel');
    lines.push(`G0 F${mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0)} X${p0.x.toFixed(3)} Y${p0.z.toFixed(3)} Z${Math.max(settings.layerHeight, p0.y).toFixed(3)}`);
    if (!emittedBrim) {
        // Mirror Orca's small restore pulse only when no brim path already primed the nozzle.
        if (settings.primeMm > 0) {
            lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E${settings.primeMm.toFixed(4)}`);
        }
        lines.push('G92 E0');
    }

    let currentLayer = p0.layer;
    lines.push('; CHANGE_LAYER');
    lines.push(`; Z_HEIGHT: ${Math.max(0.0, p0.y).toFixed(3)}`);
    lines.push(`; LAYER_HEIGHT: ${(p0.layerThicknessMm ?? settings.layerHeight).toFixed(3)}`);
    lines.push(';LAYER_CHANGE');
    lines.push(';LAYER:0');
    lines.push(`;Z:${Math.max(0.0, p0.y).toFixed(3)}`);
    lines.push('; FEATURE: Outer wall');
    lines.push(';TYPE:Outer wall');

    // Solid bottom layers: concentric inward fill rings generated from
    // each flat layer's perimeter, emitted when the layer completes.
    const bottomFillRings = new Map<number, ToolpathPoint[]>();
    if (settings.bottomLayers > 0) {
        for (const point of toolpath.points) {
            if (point.layer >= settings.bottomLayers) {
                break;
            }
            const ring = bottomFillRings.get(point.layer);
            if (ring) {
                ring.push(point);
            } else {
                bottomFillRings.set(point.layer, [point]);
            }
        }
    }

    // Feedrate is modal in Marlin/Klipper and Z rarely changes on flat
    // layers; emitting them only on change trims the file by 10-20%.
    // The travel G0 above set the travel feedrate and first-layer Z.
    let modalFeedrate = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);
    let modalZ = Math.max(settings.layerHeight, p0.y).toFixed(3);
    const travelFeedrate = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);
    let travelAfterFill = false;

    const emitBottomFill = (layerIdx: number): void => {
        const ring = bottomFillRings.get(layerIdx);
        if (!ring || ring.length < 3) {
            return;
        }
        const fillLineWidth = layerIdx === 0 ? settings.firstLayerLineWidth : settings.lineWidth;
        const fillExtrusionPerMm = calculateExtrusionPerMm(settings, fillLineWidth);
        const fillFeedrate = mmPerSecToFeedrate(
            layerIdx === 0 ? settings.firstLayerPrintSpeedMmPerSec : settings.printSpeedMmPerSec,
        ).toFixed(0);
        const ringArea = signedArea2D(ring.map((point) => ({ x: point.x, y: point.z })));
        const ringSign = Math.sign(ringArea);
        if (ringSign === 0) {
            return;
        }

        let emittedFillHeader = false;
        for (let loopIndex = 0; loopIndex < 512; loopIndex++) {
            // First ring sits ~0.9 line widths inside the perimeter for a
            // slight overlap, then rings advance by one line width.
            const inset = fillLineWidth * (0.9 + loopIndex);
            const loop = buildBrimLoop(ring, -inset);
            if (loop.length < 3) {
                break;
            }
            const loopArea = signedArea2D(loop);
            // Stop when the offset collapses: sign flip or sub-bead area.
            if (Math.sign(loopArea) !== ringSign || Math.abs(loopArea) < fillLineWidth * fillLineWidth * 2) {
                break;
            }

            // Interior fill does not need surface resolution; coarse
            // segments keep the G-code size proportional to fill area.
            const fillLoop = decimateLoop2D(loop, Math.max(0.8, settings.targetSegmentMm));
            if (fillLoop.length < 3) {
                break;
            }

            if (!emittedFillHeader) {
                lines.push('; FEATURE: Bottom surface');
                lines.push(';TYPE:Bottom surface');
                emittedFillHeader = true;
            }

            const start = fillLoop[0];
            lines.push(`G0 F${travelFeedrate} X${start.x.toFixed(3)} Y${start.y.toFixed(3)}`);
            modalFeedrate = travelFeedrate;
            let previous = start;
            let fillFeedSet = false;
            for (let pointIndex = 1; pointIndex <= fillLoop.length; pointIndex++) {
                const target = fillLoop[pointIndex % fillLoop.length];
                const distance = Math.hypot(target.x - previous.x, target.y - previous.y);
                if (distance > 1e-6) {
                    lines.push(`G1${fillFeedSet ? '' : ` F${fillFeedrate}`} X${target.x.toFixed(3)} Y${target.y.toFixed(3)} E${(distance * fillExtrusionPerMm).toFixed(5)}`);
                    fillFeedSet = true;
                    modalFeedrate = fillFeedrate;
                }
                previous = target;
            }
        }

        if (emittedFillHeader) {
            travelAfterFill = true;
        }
    };

    for (let i = 1; i < toolpath.points.length; i++) {
        const point = toolpath.points[i];
        const prevPoint = toolpath.points[i - 1];
        const layer = point.layer;
        if (layer !== currentLayer) {
            if (currentLayer < settings.bottomLayers) {
                emitBottomFill(currentLayer);
            }
            currentLayer = layer;
            lines.push('; CHANGE_LAYER');
            lines.push(`; Z_HEIGHT: ${Math.max(0.0, point.y).toFixed(3)}`);
            lines.push(`; LAYER_HEIGHT: ${(point.layerThicknessMm ?? settings.layerHeight).toFixed(3)}`);
            lines.push(';LAYER_CHANGE');
            lines.push(`;LAYER:${layer}`);
            lines.push(`;Z:${Math.max(0.0, point.y).toFixed(3)}`);
            if (layer === 1) {
                lines.push(`M106 S${configuredFanPwm}`);
            }
            if (layer >= toolpath.layerCount) {
                lines.push('; FEATURE: Top surface');
                lines.push(';TYPE:Top surface');
            } else {
                lines.push('; FEATURE: Outer wall');
                lines.push(';TYPE:Outer wall');
            }
        }

        const feedrate = mmPerSecToFeedrate(point.speedMmPerSec).toFixed(0);
        const zText = Math.max(0.0, point.y).toFixed(3);
        if (travelAfterFill) {
            // The nozzle is parked at the end of the fill; travel to the
            // next perimeter point without extruding.
            lines.push(`G0 F${travelFeedrate} X${point.x.toFixed(3)} Y${point.z.toFixed(3)} Z${zText}`);
            modalFeedrate = travelFeedrate;
            modalZ = zText;
            travelAfterFill = false;
            continue;
        }
        let line = 'G1';
        if (feedrate !== modalFeedrate) {
            line += ` F${feedrate}`;
            modalFeedrate = feedrate;
        }
        line += ` X${point.x.toFixed(3)} Y${point.z.toFixed(3)}`;
        if (zText !== modalZ) {
            line += ` Z${zText}`;
            modalZ = zText;
        }
        line += ` E${Math.max(0, point.e - prevPoint.e).toFixed(5)}`;
        lines.push(line);
    }

    const lastPoint = toolpath.points[toolpath.points.length - 1];

    if (settings.retractMm > 0) {
        lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E-${settings.retractMm.toFixed(4)}`);
    }
    lines.push('; FEATURE: Travel');
    lines.push('G0 F6000 Z' + Math.max(0.0, lastPoint.y).toFixed(3));

    const endLines = parseGcodeLines(settings.endGcode, getDefaultEndGcode());
    for (const line of endLines) {
        lines.push(expandGcodeTemplate(line, settings));
    }

    lines.push('; EXECUTABLE_BLOCK_END');

    return lines.join('\n');
}

function percentToPwm(percent: number): number {
    const clamped = clamp(percent, 0, 100);
    return Math.round((clamped / 100) * 255);
}

function appendBrimGcode(
    lines: string[],
    toolpath: VaseToolpath,
    settings: VaseSlicerSettings,
    firstLayerZ: number,
    extrusionPerMm: number
): boolean {
    const lineWidth = Math.max(0.01, settings.firstLayerLineWidth);
    const brimLoops = Math.floor(settings.brimWidthMm / lineWidth);
    const brimGap = Math.max(0, settings.brimGapMm);
    if (brimLoops <= 0 || toolpath.pointsPerLayer < 3) {
        return false;
    }

    const firstLayer = toolpath.points.filter((point) => point.layer === 0);
    if (firstLayer.length < 3) {
        return false;
    }

    const printFeed = mmPerSecToFeedrate(settings.firstLayerPrintSpeedMmPerSec).toFixed(0);
    const travelFeed = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);

    lines.push('; FEATURE: Brim');
    let isFirstBrimLoop = true;
    let emittedAnyBrimLoop = false;
    for (let loopIndex = brimLoops; loopIndex >= 1; loopIndex--) {
        const offset = lineWidth + brimGap + (loopIndex - 1) * lineWidth;
        const loop = buildBrimLoop(firstLayer, offset);
        if (loop.length < 3) {
            continue;
        }

        emittedAnyBrimLoop = true;

        const start = loop[0];
        lines.push(';TYPE:Brim');
        lines.push(`G0 F${travelFeed} X${start.x.toFixed(3)} Y${start.y.toFixed(3)} Z${firstLayerZ.toFixed(3)}`);
        if (isFirstBrimLoop) {
            if (settings.primeMm > 0) {
                lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E${(settings.primeMm * 0.75).toFixed(4)}`);
            }
            isFirstBrimLoop = false;
        }

        let previous = start;
        // The G0 above set the travel feedrate; only the first print move of
        // the loop needs to restate F.
        let brimFeedSet = false;
        for (let i = 1; i < loop.length; i++) {
            const point = loop[i];
            const distance = Math.hypot(point.x - previous.x, point.y - previous.y);
            if (distance > 0) {
                lines.push(`G1${brimFeedSet ? '' : ` F${printFeed}`} X${point.x.toFixed(3)} Y${point.y.toFixed(3)} E${(distance * extrusionPerMm).toFixed(5)}`);
                brimFeedSet = true;
            }
            previous = point;
        }

        const closingDistance = Math.hypot(start.x - previous.x, start.y - previous.y);
        if (closingDistance > 0) {
            lines.push(`G1${brimFeedSet ? '' : ` F${printFeed}`} X${start.x.toFixed(3)} Y${start.y.toFixed(3)} E${(closingDistance * extrusionPerMm).toFixed(5)}`);
        }
    }

    return emittedAnyBrimLoop;
}

function buildBrimLoop(
    source: ToolpathPoint[],
    offsetMm: number
): Array<{ x: number; y: number }> {
    // Positive offsets grow outward (brim), negative offsets shrink inward
    // (bottom fill).
    if (Math.abs(offsetMm) <= 1e-6) {
        return source.map((point) => ({ x: point.x, y: point.z }));
    }

    const contour = dedupeClosedPath2D(source.map((point) => ({ x: point.x, y: point.z })));
    if (contour.length < 3) {
        return contour;
    }

    const orientation = signedArea2D(contour);
    if (Math.abs(orientation) < 1e-9) {
        return contour;
    }

    const orientationSign = orientation >= 0 ? 1 : -1;
    const edges = buildOffsetEdges2D(contour, offsetMm, orientationSign);
    if (edges.length < 3) {
        return contour;
    }

    const miterLimit = Math.max(Math.abs(offsetMm) * 6.0, 0.5);
    const loop: Array<{ x: number; y: number }> = [];

    for (let index = 0; index < edges.length; index++) {
        const prevEdge = edges[(index - 1 + edges.length) % edges.length];
        const nextEdge = edges[index];
        const vertex = contour[index];

        const join = intersectLines2D(prevEdge.a, prevEdge.b, nextEdge.a, nextEdge.b);
        if (join && distance2D(join, vertex) <= miterLimit) {
            pushUnique2D(loop, join);
            continue;
        }

        pushUnique2D(loop, prevEdge.b);
        pushUnique2D(loop, nextEdge.a);
    }

    return dedupeClosedPath2D(loop);
}

function buildOffsetEdges2D(
    contour: Array<{ x: number; y: number }>,
    offsetMm: number,
    orientationSign: number
): Array<{ a: { x: number; y: number }; b: { x: number; y: number } }> {
    const edges: Array<{ a: { x: number; y: number }; b: { x: number; y: number } }> = [];

    for (let i = 0; i < contour.length; i++) {
        const a = contour[i];
        const b = contour[(i + 1) % contour.length];
        const dx = b.x - a.x;
        const dy = b.y - a.y;
        const length = Math.hypot(dx, dy);
        if (length <= 1e-8) {
            continue;
        }

        const tx = dx / length;
        const ty = dy / length;
        const nx = orientationSign > 0 ? ty : -ty;
        const ny = orientationSign > 0 ? -tx : tx;
        edges.push({
            a: { x: a.x + nx * offsetMm, y: a.y + ny * offsetMm },
            b: { x: b.x + nx * offsetMm, y: b.y + ny * offsetMm },
        });
    }

    return edges;
}

function signedArea2D(points: Array<{ x: number; y: number }>): number {
    let area = 0;
    for (let i = 0; i < points.length; i++) {
        const a = points[i];
        const b = points[(i + 1) % points.length];
        area += (a.x * b.y) - (b.x * a.y);
    }
    return area * 0.5;
}

/** Keeps every vertex at least minSegment apart along the loop. */
function decimateLoop2D(points: Array<{ x: number; y: number }>, minSegment: number): Array<{ x: number; y: number }> {
    if (points.length < 4) {
        return points;
    }

    const decimated: Array<{ x: number; y: number }> = [points[0]];
    let accumulated = 0;
    for (let index = 1; index < points.length; index++) {
        accumulated += distance2D(points[index - 1], points[index]);
        if (accumulated >= minSegment) {
            decimated.push(points[index]);
            accumulated = 0;
        }
    }
    return decimated;
}

function dedupeClosedPath2D(points: Array<{ x: number; y: number }>): Array<{ x: number; y: number }> {
    const deduped: Array<{ x: number; y: number }> = [];
    for (const point of points) {
        pushUnique2D(deduped, point);
    }

    if (deduped.length > 1 && distance2D(deduped[0], deduped[deduped.length - 1]) <= 1e-6) {
        deduped.pop();
    }

    return deduped;
}

function pushUnique2D(points: Array<{ x: number; y: number }>, next: { x: number; y: number }): void {
    const previous = points[points.length - 1];
    if (!previous || distance2D(previous, next) > 1e-6) {
        points.push(next);
    }
}

function distance2D(a: { x: number; y: number }, b: { x: number; y: number }): number {
    return Math.hypot(a.x - b.x, a.y - b.y);
}

function intersectLines2D(
    a0: { x: number; y: number },
    a1: { x: number; y: number },
    b0: { x: number; y: number },
    b1: { x: number; y: number }
): { x: number; y: number } | null {
    const arx = a1.x - a0.x;
    const ary = a1.y - a0.y;
    const brx = b1.x - b0.x;
    const bry = b1.y - b0.y;
    const det = (arx * bry) - (ary * brx);
    if (Math.abs(det) <= 1e-9) {
        return null;
    }

    const qpx = b0.x - a0.x;
    const qpy = b0.y - a0.y;
    const t = ((qpx * bry) - (qpy * brx)) / det;
    return {
        x: a0.x + arx * t,
        y: a0.y + ary * t,
    };
}
