import { clamp } from './math';
import { getSpiralPitchMm, type VaseSlicerSettings } from './config';
import type { ToolpathPoint, VaseToolpath } from './types';
import { calculateExtrusionPerMm } from './toolpath';
import { decimateClosedLoop, offsetOutline, offsetRegion, type Point2 } from './polygon-offset';
import {
    buildExcludeObjectDefineLine,
    buildOrcaMetadataHeader,
    inferFilamentMetadata,
} from './gcode-metadata';
import {
    expandGcodeTemplate,
    getDefaultEndGcode,
    getDefaultStartGcode,
    mmPerSecToFeedrate,
    parseGcodeLines,
} from './gcode-template';

/** Emit the final G-code for a finished toolpath. */
export function buildGcode(toolpath: VaseToolpath, settings: VaseSlicerSettings, extraHeaderLines?: string[]): string {
    if (toolpath.points.length < 2) {
        throw new Error('Vase slicing produced no valid path.');
    }

    const lines: string[] = [];
    const p0 = toolpath.points[0];
    const configuredFanPwm = percentToPwm(settings.fanPercent);
    const filamentMeta = inferFilamentMetadata(settings);

    lines.push(...buildOrcaMetadataHeader(toolpath, settings, filamentMeta));

    const excludeObjectDefine = buildExcludeObjectDefineLine(toolpath, settings);
    if (excludeObjectDefine) {
        lines.push(excludeObjectDefine);
    }

    lines.push('; Implicit vase-mode toolpath');
    lines.push('; Generated by Implicit');
    lines.push(`; Slicer mode: ${settings.slicerMode}`);
    lines.push(`; Layers: ${toolpath.layerCount}`);
    lines.push(`; Points per layer: ${toolpath.pointsPerLayer}`);
    lines.push(`; Model scale (mm/SDF-unit): ${settings.modelScale.toFixed(2)}`);
    lines.push(`; Printer: ${settings.printerModelName} (${settings.printerModelId})`);
    lines.push(`; Filament: ${settings.filamentProfileName} (${settings.filamentProfileId})`);
    lines.push(`; Filament type: ${filamentMeta.type}`);
    lines.push(`; Filament density (g/cm3): ${filamentMeta.densityGcm3.toFixed(2)}`);
    lines.push(`; Filament cost (per kg): ${filamentMeta.costPerKg.toFixed(2)}`);
    lines.push(`; Bed size (mm): ${settings.bedWidthMm.toFixed(1)} x ${settings.bedDepthMm.toFixed(1)}`);
    lines.push(`; Max print height (mm): ${settings.maxPrintHeightMm.toFixed(1)}`);
    lines.push(`; Nozzle diameter (mm): ${settings.nozzleDiameter.toFixed(2)}`);
    lines.push(`; Nozzle temperature (C): ${settings.nozzleTempC.toFixed(0)}`);
    lines.push(`; Bed temperature (C): ${settings.bedTempC.toFixed(0)}`);
    lines.push(`; Fan speed (%): ${settings.fanPercent.toFixed(0)}`);
    lines.push(`; Line width (mm): ${settings.lineWidth.toFixed(3)}`);
    lines.push(`; First layer line width (mm): ${settings.firstLayerLineWidth.toFixed(3)}`);
    lines.push(`; Layer height (mm): ${settings.layerHeight.toFixed(3)}`);
    if (settings.maxLayerHeightMm > settings.layerHeight) {
        lines.push(`; Max layer height (mm): ${settings.maxLayerHeightMm.toFixed(3)}`);
    }
    if (getSpiralPitchMm(settings) > 0) {
        lines.push(`; Spiral pitch (mm): ${getSpiralPitchMm(settings).toFixed(3)}`);
    }
    lines.push(`; Target segment length (mm): ${settings.targetSegmentMm.toFixed(3)}`);
    lines.push(`; First layer print speed (mm/s): ${settings.firstLayerPrintSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Print speed (mm/s): ${settings.printSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Minimum layer time (s): ${settings.minLayerTimeSec.toFixed(2)}`);
    lines.push(`; Travel speed (mm/s): ${settings.travelSpeedMmPerSec.toFixed(1)}`);
    lines.push(`; Bottom layers: ${settings.bottomLayers}`);
    lines.push(`; Brim width (mm): ${settings.brimWidthMm.toFixed(2)}`);
    lines.push(`; Brim gap (mm): ${settings.brimGapMm.toFixed(2)}`);
    lines.push(`; Iso snap factor: ${settings.sliceIsoSnapFactor.toFixed(2)}`);
    lines.push(`; Contour alignment: ${settings.enableContourAlignment ? 'on' : 'off'}`);
    lines.push(`; Move merging: ${settings.enableMoveMerging ? 'on' : 'off'}`);
    lines.push(`; First layer extrusion/mm: ${calculateExtrusionPerMm(settings, settings.firstLayerLineWidth).toFixed(5)}`);
    lines.push(`; Extrusion/mm: ${calculateExtrusionPerMm(settings, settings.lineWidth).toFixed(5)}`);
    lines.push(`; Estimated height (mm): ${toolpath.estimatedHeight.toFixed(3)}`);
    for (const summary of toolpath.postprocessSummaries ?? []) {
        lines.push(`; Postprocess step ${summary.stepIndex + 1}: ${summary.name}${summary.scriptId ? ` (${summary.scriptId})` : ''}`);
        lines.push(`; Postprocess points: ${summary.inputPointCount} -> ${summary.outputPointCount} before merge`);
        lines.push(`; Postprocess runtime (ms): ${summary.durationMs.toFixed(2)}`);
        for (const note of summary.notes) {
            lines.push(`; Postprocess note: ${note}`);
        }
    }
    for (const line of extraHeaderLines ?? []) {
        lines.push(line.startsWith(';') ? line : `; ${line}`);
    }
    const rawPathPoints = toolpath.layerCount * toolpath.pointsPerLayer;
    const mergedPathPoints = toolpath.points.length;
    const removedPathPoints = Math.max(0, rawPathPoints - mergedPathPoints);
    const mergeReductionPct = rawPathPoints > 0 ? (removedPathPoints / rawPathPoints) * 100 : 0;
    lines.push(`; Move merge: ${removedPathPoints} points removed (${mergeReductionPct.toFixed(1)}%)`);
    const startLines = parseGcodeLines(settings.startGcode, getDefaultStartGcode());
    for (const line of startLines) {
        lines.push(expandGcodeTemplate(line, settings));
    }
    // Normalize motion/extrusion modes regardless of custom start G-code state.
    lines.push('G21');
    lines.push('G90');
    // Force relative extrusion for exported toolpaths so each move carries only its local extrusion delta.
    lines.push('M83');
    // Keep first layer fan off for adhesion, then restore configured fan after layer 0.
    lines.push('M106 S0');
    const emittedBrim = appendBrimGcode(
        lines,
        toolpath,
        settings,
        Math.max(settings.layerHeight, p0.y),
        calculateExtrusionPerMm(settings, settings.firstLayerLineWidth)
    );
    lines.push('; FEATURE: Travel');
    lines.push(`G0 F${mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0)} X${p0.x.toFixed(3)} Y${p0.z.toFixed(3)} Z${Math.max(settings.layerHeight, p0.y).toFixed(3)}`);
    if (!emittedBrim) {
        // Mirror Orca's small restore pulse only when no brim path already primed the nozzle.
        if (settings.primeMm > 0) {
            lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E${settings.primeMm.toFixed(4)}`);
        }
        lines.push('G92 E0');
    }

    let currentLayer = p0.layer;
    lines.push('; CHANGE_LAYER');
    lines.push(`; Z_HEIGHT: ${Math.max(0.0, p0.y).toFixed(3)}`);
    lines.push(`; LAYER_HEIGHT: ${(p0.layerThicknessMm ?? settings.layerHeight).toFixed(3)}`);
    lines.push(';LAYER_CHANGE');
    lines.push(';LAYER:0');
    lines.push(`;Z:${Math.max(0.0, p0.y).toFixed(3)}`);
    lines.push('; FEATURE: Outer wall');
    lines.push(';TYPE:Outer wall');

    // Solid bottom layers: concentric inward fill rings generated from
    // each flat layer's perimeter, emitted when the layer completes.
    const bottomFillRings = collectBottomLayerRings(toolpath, settings);

    // Feedrate is modal in Marlin/Klipper and Z rarely changes on flat
    // layers; emitting them only on change trims the file by 10-20%.
    // The travel G0 above set the travel feedrate and first-layer Z.
    let modalFeedrate = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);
    let modalZ = Math.max(settings.layerHeight, p0.y).toFixed(3);
    const travelFeedrate = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);
    let travelAfterFill = false;

    const emitBottomFill = (layerIdx: number): void => {
        const ring = bottomFillRings.get(layerIdx);
        if (!ring || ring.length < 3) {
            return;
        }
        const fillLineWidth = layerIdx === 0 ? settings.firstLayerLineWidth : settings.lineWidth;
        const fillExtrusionPerMm = calculateExtrusionPerMm(settings, fillLineWidth);
        const fillFeedrate = mmPerSecToFeedrate(
            layerIdx === 0 ? settings.firstLayerPrintSpeedMmPerSec : settings.printSpeedMmPerSec,
        ).toFixed(0);

        let emittedFillHeader = false;
        for (const fillLoop of buildBottomFillLoopSet(ring, layerIdx, settings)) {
            if (!emittedFillHeader) {
                lines.push('; FEATURE: Bottom surface');
                lines.push(';TYPE:Bottom surface');
                emittedFillHeader = true;
            }

            const start = fillLoop[0];
            lines.push(`G0 F${travelFeedrate} X${start.x.toFixed(3)} Y${start.y.toFixed(3)}`);
            modalFeedrate = travelFeedrate;
            let previous = start;
            let fillFeedSet = false;
            for (let pointIndex = 1; pointIndex <= fillLoop.length; pointIndex++) {
                const target = fillLoop[pointIndex % fillLoop.length];
                const distance = Math.hypot(target.x - previous.x, target.y - previous.y);
                if (distance > 1e-6) {
                    lines.push(`G1${fillFeedSet ? '' : ` F${fillFeedrate}`} X${target.x.toFixed(3)} Y${target.y.toFixed(3)} E${(distance * fillExtrusionPerMm).toFixed(5)}`);
                    fillFeedSet = true;
                    modalFeedrate = fillFeedrate;
                }
                previous = target;
            }
        }

        if (emittedFillHeader) {
            travelAfterFill = true;
        }
    };

    for (let i = 1; i < toolpath.points.length; i++) {
        const point = toolpath.points[i];
        const prevPoint = toolpath.points[i - 1];
        const layer = point.layer;
        if (layer !== currentLayer) {
            if (currentLayer < settings.bottomLayers) {
                emitBottomFill(currentLayer);
            }
            currentLayer = layer;
            lines.push('; CHANGE_LAYER');
            lines.push(`; Z_HEIGHT: ${Math.max(0.0, point.y).toFixed(3)}`);
            lines.push(`; LAYER_HEIGHT: ${(point.layerThicknessMm ?? settings.layerHeight).toFixed(3)}`);
            lines.push(';LAYER_CHANGE');
            lines.push(`;LAYER:${layer}`);
            lines.push(`;Z:${Math.max(0.0, point.y).toFixed(3)}`);
            if (layer === 1) {
                lines.push(`M106 S${configuredFanPwm}`);
            }
            if (layer >= toolpath.layerCount) {
                lines.push('; FEATURE: Top surface');
                lines.push(';TYPE:Top surface');
            } else {
                lines.push('; FEATURE: Outer wall');
                lines.push(';TYPE:Outer wall');
            }
        }

        const feedrate = mmPerSecToFeedrate(point.speedMmPerSec).toFixed(0);
        const zText = Math.max(0.0, point.y).toFixed(3);
        if (travelAfterFill) {
            // The nozzle is parked at the end of the fill; travel to the
            // next perimeter point without extruding.
            lines.push(`G0 F${travelFeedrate} X${point.x.toFixed(3)} Y${point.z.toFixed(3)} Z${zText}`);
            modalFeedrate = travelFeedrate;
            modalZ = zText;
            travelAfterFill = false;
        } else if (point.travel) {
            // Script-authored travel: same modal F/Z handling, no extrusion.
            let line = 'G0';
            if (feedrate !== modalFeedrate) {
                line += ` F${feedrate}`;
                modalFeedrate = feedrate;
            }
            line += ` X${point.x.toFixed(3)} Y${point.z.toFixed(3)}`;
            if (zText !== modalZ) {
                line += ` Z${zText}`;
                modalZ = zText;
            }
            lines.push(line);
        } else {
            let line = 'G1';
            if (feedrate !== modalFeedrate) {
                line += ` F${feedrate}`;
                modalFeedrate = feedrate;
            }
            line += ` X${point.x.toFixed(3)} Y${point.z.toFixed(3)}`;
            if (zText !== modalZ) {
                line += ` Z${zText}`;
                modalZ = zText;
            }
            line += ` E${Math.max(0, point.e - prevPoint.e).toFixed(5)}`;
            lines.push(line);
        }

        const dwellMs = Math.round(point.dwellAfterMs ?? 0);
        if (dwellMs > 0) {
            lines.push(`G4 P${dwellMs}`);
        }
    }

    const lastPoint = toolpath.points[toolpath.points.length - 1];

    if (settings.retractMm > 0) {
        lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E-${settings.retractMm.toFixed(4)}`);
    }
    lines.push('; FEATURE: Travel');
    lines.push('G0 F6000 Z' + Math.max(0.0, lastPoint.y).toFixed(3));

    const endLines = parseGcodeLines(settings.endGcode, getDefaultEndGcode());
    for (const line of endLines) {
        lines.push(expandGcodeTemplate(line, settings));
    }

    lines.push('; EXECUTABLE_BLOCK_END');

    return lines.join('\n');
}

/** A closed 2D loop in bed coordinates (X, Y = the toolpath's X, Z). */
export type SupportLoop2D = Array<{ x: number; y: number }>;

/**
 * Groups the points of each solid bottom layer into that layer's perimeter
 * ring. Only the flat layers below `bottomLayers` get concentric fill.
 */
export function collectBottomLayerRings(
    toolpath: VaseToolpath,
    settings: VaseSlicerSettings,
): Map<number, ToolpathPoint[]> {
    const rings = new Map<number, ToolpathPoint[]>();
    if (settings.bottomLayers <= 0) {
        return rings;
    }

    for (const point of toolpath.points) {
        if (point.layer >= settings.bottomLayers) {
            break;
        }
        const ring = rings.get(point.layer);
        if (ring) {
            ring.push(point);
        } else {
            rings.set(point.layer, [point]);
        }
    }

    return rings;
}

/**
 * Brim loops for the first layer, in print order (outermost first).
 *
 * Split out from emission so the preview can draw the same loops the printer
 * will run: brim and bottom fill are generated here rather than in the
 * toolpath, and would otherwise exist only as text in the exported file.
 *
 * Each ring is grown from the one inside it by a line width rather than from
 * the outline by its full distance; see polygon-offset.ts for why that is
 * both exact and cheap. A ring can come back as several loops - an inlet in
 * the first layer pinching shut leaves its chamber as a hole - and every
 * loop of a ring is printed.
 */
export function buildBrimLoopSet(toolpath: VaseToolpath, settings: VaseSlicerSettings): SupportLoop2D[] {
    const lineWidth = Math.max(0.01, settings.firstLayerLineWidth);
    const brimLoops = Math.floor(settings.brimWidthMm / lineWidth);
    const brimGap = Math.max(0, settings.brimGapMm);
    if (brimLoops <= 0 || toolpath.pointsPerLayer < 3) {
        return [];
    }

    const firstLayer = toolpath.points.filter((point) => point.layer === 0);
    if (firstLayer.length < 3) {
        return [];
    }

    const options = { minArea: lineWidth * lineWidth, maxStep: lineWidth };
    const rings: Point2[][][] = [];
    let ring = offsetOutline(bedOutline(firstLayer), lineWidth + brimGap, options);
    for (let loopIndex = 0; loopIndex < brimLoops && ring.length > 0; loopIndex++) {
        rings.push(ring);
        ring = offsetRegion(ring, lineWidth, options);
    }

    return rings.reverse().flat();
}

/**
 * Concentric inward fill loops for one solid bottom layer, outermost first.
 *
 * The first ring sits 0.9 line widths inside the perimeter for a slight
 * overlap, and each further ring shrinks the last by a line width, so the
 * spacing between neighbouring rings is exact wherever the outline goes. A
 * ring that pinches through a narrow waist comes back as two islands, both
 * printed; the fill ends when nothing larger than a couple of bead
 * cross-sections is left.
 */
export function buildBottomFillLoopSet(
    ring: ToolpathPoint[],
    layerIndex: number,
    settings: VaseSlicerSettings,
): SupportLoop2D[] {
    if (ring.length < 3) {
        return [];
    }

    const fillLineWidth = layerIndex === 0 ? settings.firstLayerLineWidth : settings.lineWidth;
    const options = { minArea: fillLineWidth * fillLineWidth * 2, maxStep: fillLineWidth };
    // Interior fill does not need surface resolution; coarse segments keep
    // the G-code size proportional to fill area.
    const fillSegmentMm = Math.max(0.8, settings.targetSegmentMm);
    const coarsen = (loops: Point2[][]) => loops.map((loop) => decimateClosedLoop(loop, fillSegmentMm));

    const loops: SupportLoop2D[] = [];
    let current = coarsen(offsetOutline(bedOutline(ring), -fillLineWidth * 0.9, options));
    for (let step = 0; step < 512 && current.length > 0; step++) {
        loops.push(...current);
        current = coarsen(offsetRegion(current, -fillLineWidth, options));
    }

    return loops;
}

/** A toolpath ring as a closed outline in bed coordinates (X, Y = the toolpath's X, Z). */
function bedOutline(points: ToolpathPoint[]): Point2[] {
    return points.map((point) => ({ x: point.x, y: point.z }));
}

function percentToPwm(percent: number): number {
    const clamped = clamp(percent, 0, 100);
    return Math.round((clamped / 100) * 255);
}

function appendBrimGcode(
    lines: string[],
    toolpath: VaseToolpath,
    settings: VaseSlicerSettings,
    firstLayerZ: number,
    extrusionPerMm: number
): boolean {
    const brimLoopSet = buildBrimLoopSet(toolpath, settings);
    if (brimLoopSet.length === 0) {
        return false;
    }

    const printFeed = mmPerSecToFeedrate(settings.firstLayerPrintSpeedMmPerSec).toFixed(0);
    const travelFeed = mmPerSecToFeedrate(settings.travelSpeedMmPerSec).toFixed(0);

    lines.push('; FEATURE: Brim');
    let isFirstBrimLoop = true;
    for (const loop of brimLoopSet) {
        const start = loop[0];
        lines.push(';TYPE:Brim');
        lines.push(`G0 F${travelFeed} X${start.x.toFixed(3)} Y${start.y.toFixed(3)} Z${firstLayerZ.toFixed(3)}`);
        if (isFirstBrimLoop) {
            if (settings.primeMm > 0) {
                lines.push(`G1 F${mmPerSecToFeedrate(settings.retractSpeedMmPerSec).toFixed(0)} E${(settings.primeMm * 0.75).toFixed(4)}`);
            }
            isFirstBrimLoop = false;
        }

        let previous = start;
        // The G0 above set the travel feedrate; only the first print move of
        // the loop needs to restate F.
        let brimFeedSet = false;
        for (let i = 1; i < loop.length; i++) {
            const point = loop[i];
            const distance = Math.hypot(point.x - previous.x, point.y - previous.y);
            if (distance > 0) {
                lines.push(`G1${brimFeedSet ? '' : ` F${printFeed}`} X${point.x.toFixed(3)} Y${point.y.toFixed(3)} E${(distance * extrusionPerMm).toFixed(5)}`);
                brimFeedSet = true;
            }
            previous = point;
        }

        const closingDistance = Math.hypot(start.x - previous.x, start.y - previous.y);
        if (closingDistance > 0) {
            lines.push(`G1${brimFeedSet ? '' : ` F${printFeed}`} X${start.x.toFixed(3)} Y${start.y.toFixed(3)} E${(closingDistance * extrusionPerMm).toFixed(5)}`);
        }
    }

    return true;
}
